In [6]:
import pandas as pd
import sqlite3
from pandas.plotting import scatter_matrix

In [7]:
connect = sqlite3.connect('data/checking-logs.sqlite')

## Посмотрим, какие таблицы есть в базе test и control это таблицы, которые мы сами создали (выборки)

In [8]:
a = connect.cursor().execute('SELECT name from sqlite_master where type= "table"')
print(a.fetchall())

[('pageviews',), ('checker',), ('deadlines',), ('test',), ('control',)]

In [9]:
query = '''
SELECT uid, COUNT(*) AS num_commits
FROM checker
WHERE uid LIKE 'user_%'
AND labname <> 'project1'
GROUP BY uid
'''
commits = pd.io.sql.read_sql(query, connect)
commits

        uid  num_commits
0    user_0            3
1    user_1           62
2   user_10           20
3   user_11            7
4   user_12           86
5   user_13           52
6   user_14           61
7   user_15           23
8   user_16           41
9   user_17           51
10  user_18            5
11  user_19          118
12   user_2           46
13  user_20           57
14  user_21           65
15  user_22            5
16  user_23            6
17  user_24           37
18  user_25           79
19  user_26           36
20  user_27           27
21  user_28           60
22  user_29           51
23   user_3           18
24  user_30           34
25  user_31          128
26   user_4           40
27   user_6           15
28   user_7            8
29   user_8           71

## Создадим таблицу с количеством просмотров

In [10]:
query = '''
SELECT uid, COUNT(*) AS num_views
FROM pageviews
WHERE uid LIKE 'user_%'
GROUP BY uid
'''
num_views = pd.io.sql.read_sql(query, connect)
num_views

        uid  num_views
0    user_1         28
1   user_10         89
2   user_14        143
3   user_17         47
4   user_18          3
5   user_19         16
6   user_21         10
7   user_25        179
8   user_28        149
9    user_3        317
10  user_30          3
11   user_5          1
12   user_9          2

#### Создадим таблицу с дельтой: разница между первым коммитом и дедлайном лаборатории (подробно, как мы это делали в Day06 ех03). (Не принимать во внимание project1 для расчета средней разницы и количества коммитов)

In [11]:
query = '''
SELECT uid,
       CAST((JulianDay(test.first_commit_ts) -
            JulianDay(DATETIME(deadlines.deadlines, 'unixepoch'))
                  ) * 24 AS Integer
           ) AS delta
FROM test
LEFT JOIN deadlines ON test.labname=deadlines.labs
WHERE labname <> 'project1'
'''
delta = pd.io.sql.read_sql(query, connect)
delta

        uid  delta
0   user_30   -202
1   user_30   -201
2   user_14   -200
3   user_14   -193
4   user_19   -148
5   user_25   -148
6   user_21   -126
7   user_21    -99
8   user_28    -98
9   user_17    -81
10   user_3    -75
11   user_3    -75
12  user_10    -39
13  user_10    -39
14  user_17    -35
15  user_28     -8
16   user_1     -6
17   user_1     -6
18  user_18     -4
19  user_18     -3
20  user_25     -2
21  user_14    -84
22   user_3    -60
23  user_25    -58
24  user_28    -53
25  user_10    -52
26  user_30    -52
27  user_17    -34
28  user_21    -33
29  user_19    -32
30   user_1    -28
31  user_18    -10
32   user_3   -182
33   user_1   -175
34  user_28   -174
35  user_25   -150
36   user_3   -135
37  user_19   -133
38  user_10   -132
39  user_30   -126
40  user_21   -124
41  user_10   -112
42   user_1   -107
43  user_25   -105
44  user_28    -99
45  user_19    -82
46  user_17    -80
47  user_17    -78

In [12]:
connect.close()